### ISSUE TITLE
Where is the Assay sidebar

### ISSUE THREAD

**Issue by ialecse** [mozilla/assay#129]
Documentation talks about _Assay sidebar_ , Assay was installed in VSC, but I couldn't find any sidebar for it.

**Comment by chrstinalin** [comment]
There's a possibility it's minimized under your 'explorer' panel --
![image](https://github.com/user-attachments/assets/1392e939-b3ba-49e6-931a-51fa1280d3b4)

If not, check if it's selected under the available views for the explorer:
![image](https://github.com/user-attachments/assets/12ee2f02-3217-4452-87a9-aa13eb39b58e)

**Comment by ialecse** [comment]
I was not expecting the sidebar to be named Addons, but "Assay" as the documentation refers to "Assay sidebar". I found it now, but either the documentation should be updated to make it clear how the sidebar is named or the sidebar's title should be changed.
