### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by diox** [mozilla/assay#3]
Here are the things I noticed when doing a first pass that are a bit more specific than what was mentioned in https://github.com/mozilla/assay/issues/2. Some of them you are probably already aware but I want to list everything so we don't forget: 

**General:**
- Use OS path separator instead of `/` everywhere (`path.sep`)
- There are a bunch of hardcoded URLs that should be constants instead. I'd suggest having a constants file with the URL paths, and a config to decide if we should hit dev/stage/prod.
- There are a lot of error cases to handle a bit more gracefully - rejecting promises where applicable and showing a nice error to the user so that they can re-attempt the failed operation or something, instead of silently not doing anything.

**File by file:**
https://github.com/mozilla/assay/blob/main/src/amo/interfaces.ts
- Might want to use a camelCase naming structure for AddonInfoResponse (we have done that in addons-frontend)

https://github.com/mozilla/assay/blob/main/src/amo/commands/fetch.ts
- We probably want a function that returns the add-on folder from an add-on guid + version. That logic is hidden in the downloadAndExtract() at the moment

https://github.com/mozilla/assay/blob/main/src/amo/commands/updateTaskbar.ts
- Different way of checking that our add-on "guid" is a guid or not, also should be in an util somewhere
- Not sure why you are fetching the review page

https://github.com/mozilla/assay/blob/main/src/amo/utils/addonDownload.ts
- Probably call the `id` `file_id` to make it clear what it is.

https://github.com/mozilla/assay/blob/main/src/amo/utils/addonInfo.ts
- Could be rewritten with less duplicated code

https://github.com/mozilla/assay/blob/main/src/amo/utils/addonVersions.ts
- Could be rewritten with less duplicated code as above. Some of the logic to call the API should probably be in an util somewhere.
- Later when we add auth we'll want to revisit getAddonVersions to also download non-public versions.

**Comment by eviljeff** [comment]
btw, I added a bunch of comments to lines - but as github doesn't let you comment on files, I commented on the commit that last touched the line.  (seemed like a good idea at the time!)

**Comment by diox** [comment]
Might have been smarter than my technique of copy/pasting file links in that giant comment...

**Comment by GregSherman** [comment]
> Not sure why you are fetching the review page
I've done this to ensure that the taskbar item will either not exist or point to the correct page. I check to ensure the page is there in cases where a user may have edited the folder names. I CAN get rid of it since this error is mitigated by relying on an already sound api and the user of the extension is a reviewer and competent. But it may be useful to see at a glance that the taskbar item points to an invalid URL (by updating the text when 404 occurs)

**Comment by GregSherman** [comment]
> There are a lot of error cases to handle a bit more gracefully - rejecting promises where applicable and showing a nice error to the user so that they can re-attempt the failed operation or something, instead of silently not doing anything.

In addition to this, all errors currently just return undefined. This is troublesome for tests because I can't access the error messages that vscode produces, so I'm wondering if there's some convention for testing errors based on return value. Having a unique code for each error return statement is easy but seems wrong

**Comment by diox** [comment]
> > Not sure why you are fetching the review page
> 
> I've done this to ensure that the taskbar item will either not exist or point to the correct page. I check to ensure the page is there in cases where a user may have edited the folder names. I CAN get rid of it since this error is mitigated by relying on an already sound api and the user of the extension is a reviewer and competent. But it may be useful to see at a glance that the taskbar item points to an invalid URL (by updating the text when 404 occurs)

Ok. I'm not sure how valuable that is, but if we want to keep something like this we should replace the URL being hit by an API call and cache it for the session.



>> There are a lot of error cases to handle a bit more gracefully - rejecting promises where applicable and showing a nice error to the user so that they can re-attempt the failed operation or something, instead of silently not doing anything.
>
> In addition to this, all errors currently just return undefined. This is troublesome for tests because I can't access the error messages that vscode produces, so I'm wondering if there's some convention for testing errors based on return value. Having a unique code for each error return statement is easy but seems wrong

I would split up code more and do more unit tests for various cases, where you know which function you are testing. 

On top of this, something we have done in the past (that I don't particularly like though) is allowing global/external objects to be overridden in the functions using them, to more easily mock these in tests. You can see this trick in action in a lot of `addons-frontend` code, with the arguments starting with an underscore and tests taking advantage of that (look for patterns with `{ _someFunction = someFunction }` when declaring the function)
