### ISSUE TITLE
Clicking "Open in VSC" button in reviewer tools only opens the manifest.json file of the selected add-on version

### ISSUE THREAD

**Issue by abhn** [mozilla/assay#30]
## Description
- When the "Open in VSC" button is clicked, only the manifest.json file of that add-on version is opened in the currently open VSC session, without any other files. 
- To see other files, I have to go File > Open Folder and then select the version that was downloaded but not opened properly.

## STR
- Keep VSCode session open with a project
- Go to AMO reviewer tools and select and add-on for review
- Click "Open in VSC" button for a version

## Expectations
- VSC opens the selected add-on version in either a new or existing VSC window with all the files

## What happened
- VSC opens the manifest.json in the current window without any other files

**Comment by abhn** [comment]
@GregSherman Do you need any more info here? This issue is making the extension pretty unusable for our reviewers.

**Comment by GregSherman** [comment]
> @GregSherman Do you need any more info here? This issue is making the extension pretty unusable for our reviewers. 

No more info needed, but I'll get on this very soon
