### ISSUE TITLE
Integrate add-ons linter in assay

### ISSUE THREAD

**Issue by abhn** [mozilla/assay#35]
Currently our code manager shows inline lint offences like potential unsafe DOM injections etc when browsing add-on code. 

We should migrate this feature to Assay to help reviewers with visual cues to interesting parts of the source code.

Ref: https://github.com/mozilla/addons-linter/

**Comment by abhn** [comment]
Please note that `addons-code-manager` calls an API to fetch the validation messages for each version of the add-on.
https://github.dev/mozilla/addons-code-manager/blob/db00e5c6bf62c127890c61ff7fbceb7e2742a86e/src/api/index.tsx#L540-L541

On the `addons-server` side, this seems to be the implementation: 
https://github.dev/mozilla/addons-server/blob/070856d633d3cfdf437440916e744cdd3970acf5/src/olympia/reviewers/views.py#L1197-L1198

I'm not sure, but it seems like the validation messages are stored on the `file` itself (perhaps generated during submission time?). Not sure how helpful that was, but hopefully that's a start.

For our vscode linter, we'd probably want to directly use addons-linter inside vscode (assay?) itself without any preprocessing.

**Comment by camsterrrr** [comment]
@abhn 

Thanks for the comments! I noticed you didn't mention anything about language servers, I'm curious what your thoughts are on this...

In our email thread, Simeon put us on to language servers. This is what we've been looking into and prototyping for the last few days. 
VSCode Docs: https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#why-language-server 
Microsoft Docs: https://microsoft.github.io/language-server-protocol/ 

* _I believe the biggest point in using this approach is to separate the overhead of the linting process from the Assay extension's running process._ * 

I'm curious what your/everyone's thoughts are on the language server? Is this still a good approach to use? 

I have been thinking of a road map for developing the language server functionality, but for brevity I'll wait to hear what you/everyone thinks about using this approach moving forward.
