### ISSUE TITLE
Switch To Using ExtensionContext.globalState to Store Comments Rather Than On User's Filesystem

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/assay#48]
>I was curious when (if ever) the `workspace` arg would be undefined, so I started poking through some VSCode docs. While trying to look up information about `vscode.ExtensionContext` I found [some docs](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage) that state (emphasis mine):

> [ExtensionContext.globalState](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalState): **A global storage where you can write key/value pairs. VS Code manages the storage and will restore it for each extension activation.** You can selectively synchronize key/value pairs in global storage by setting the keys for sync using setKeysForSync method on globalState.

> On the surface this seems like it would be preferable to use this over manually reading/writing our own files on the user's filesystem.

_Originally posted by @dotproto in https://github.com/mozilla/assay/pull/41#discussion_r1617561204_

**Comment by wagnerand** [comment]
Comments have been removed.

**Comment by wagnerand** [comment]
Ah, sorry I had understood from the original title that it is about comments.

**Comment by chrstinalin** [comment]
It technically was, since comments was the most relevant example (and what uncovered this in the first place), but its not the _only_ application of it.
