### ISSUE TITLE
Remove commenting functionality

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/assay#90]
Remove the commenting functionality from Assay, so that it is only used as a version inspection and comparison tool.

**Comment by chrstinalin** [comment]
This is possible, I'd just like to note it's removing a significant chunk of the codebase.

Is there no situation in which the commenting is useful? Would the ability to right click to mark lines be beneficial on top of the existing commenting rather than in stead of?

**Comment by abyrne-moz** [comment]
The primary goal of Assay is to replace the online code manager tool, and the reviewers do not use any commenting system in there to my knowledge.  After speaking with @willdurand, @wagnerand and @abhn we decided it would be best to remove code for features that will not be used to make the codebase smaller, easier to maintain and reduce the risk of bugs.

**Comment by chrstinalin** [comment]
@abyrne-moz There is technically one, but it's not the first time I've heard that it wasn't being used. 
![image](https://github.com/user-attachments/assets/61febacc-7617-473f-8ca2-73416493b336)
