### ISSUE TITLE
Copy line number along with code

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/assay#92]
Allow a reviewer to copy a line of code, along with the associated line number, so it can be pasted into a developer reply.

**Comment by chrstinalin** [comment]
Is there a particular format in mind? Or is something like:

folder/file.py#24
<lines of code>

ample?

**Comment by abyrne-moz** [comment]
@wagnerand Can you please provide a suggestion for the format you'd like to see here?

**Comment by wagnerand** [comment]
` * src/path/file.js#256`
