### ISSUE TITLE
Default diff to BComp

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/assay#94]
Set the default diff tool to bcomp so that there are less setup steps involved.

If we use the string "bcomp" it should launch properly on both Mac and Windows.

**Comment by chrstinalin** [comment]
This is trivial to add, I'd just like to note that:

> If we use the string "bcomp" it should launch properly on both Mac and Windows.

This wasn't the case for when I tested on my personal Windows machine -- I had to use `BComp.exe` rather than `bcomp`, and that was only after some PATH configuration.

**Comment by wagnerand** [comment]
I misremembered the difference between `bcomp` and `bcompare`. We should use `bcompare`
